-- 50-item demo catalog (photos: public/images/products/demo, credits in CREDITS.md).
-- Generated; safe to re-run (skips slugs that already exist).

insert into categories (slug, name_id, name_en, sort) values ('tops', 'Atasan', 'Tops', 2)
on conflict (slug) do nothing;
update categories set sort = case slug when 'pants' then 1 when 'tops' then 2 when 'outerwear' then 3 when 'footwear' then 4 else 5 end;

with v(slug, type, cat, name_id, name_en, desc_id, desc_en, price, compare_at, cond, cond_id, cond_en, meas) as (values
  ('khaki-pleated-chinos','thrift','pants','Khaki Pleated Chinos','Khaki Pleated Chinos','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',285000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":82,"length":104,"inseam":76,"thigh":33,"leg_opening":21}'),
  ('woodland-camo-cargo','thrift','pants','Woodland Camo Cargo Pants','Woodland Camo Cargo Pants','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',395000,475000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"waist":84,"length":106,"inseam":78,"thigh":35,"leg_opening":24}'),
  ('leopard-print-wide-pants','thrift','pants','Leopard Print Wide Pants','Leopard Print Wide Pants','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',325000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":74,"length":102,"inseam":74,"thigh":34,"leg_opening":30}'),
  ('navy-wool-pleated-trousers','thrift','pants','Navy Wool Pleated Trousers','Navy Wool Pleated Trousers','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',450000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"waist":80,"length":105,"inseam":78,"thigh":34,"leg_opening":23}'),
  ('light-wash-straight-jeans','thrift','pants','Light Wash Straight Jeans','Light Wash Straight Jeans','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',365000,425000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":82,"length":107,"inseam":80,"thigh":32,"leg_opening":22}'),
  ('studded-blue-jeans','thrift','pants','Studded Blue Jeans','Studded Blue Jeans','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',345000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"waist":77,"length":104,"inseam":78,"thigh":31,"leg_opening":20}'),
  ('raw-indigo-denim','thrift','pants','Raw Indigo Denim','Raw Indigo Denim','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',525000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":84,"length":108,"inseam":81,"thigh":33,"leg_opening":21}'),
  ('selvedge-red-tab-jeans','thrift','pants','Selvedge Red Tab Jeans','Selvedge Red Tab Jeans','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',575000,650000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":80,"length":107,"inseam":81,"thigh":32,"leg_opening":21}'),
  ('usa-colorblock-swim-shorts','thrift','pants','USA Color-Block Shorts','USA Color-Block Shorts','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',245000,295000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":80,"length":46}'),
  ('polo-colorblock-shorts','thrift','pants','Color-Block Sport Shorts','Color-Block Sport Shorts','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',225000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"waist":84,"length":45}'),
  ('navy-sport-bike-shorts','thrift','pants','Navy Sport Bike Shorts','Navy Sport Bike Shorts','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',165000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"waist":76,"length":50}'),
  ('turquoise-boardshorts','merch','pants','Turquoise Boardshorts','Turquoise Boardshorts','Celana pilihan dengan potongan yang gampang dipadu. Dicek, dicuci, dan siap pakai.','Hand-picked pants with an easy-to-style cut. Checked, washed, and ready to wear.',179000,219000,null,'','','{}'),
  ('black-leather-zip-jacket','thrift','outerwear','Black Leather Zip Jacket','Black Leather Zip Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',895000,1150000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":58,"length":70,"sleeve":63}'),
  ('yellow-canvas-work-jacket','thrift','outerwear','Yellow Canvas Work Jacket','Yellow Canvas Work Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',425000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":62,"length":72,"sleeve":64}'),
  ('navy-green-varsity-jacket','thrift','outerwear','Navy & Green Varsity Jacket','Navy & Green Varsity Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',545000,650000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":60,"length":68,"sleeve":64}'),
  ('black-stadium-jacket','thrift','outerwear','Black Stadium Jacket','Black Stadium Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',475000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":57,"length":66,"sleeve":62}'),
  ('navy-red-colorblock-windbreaker','thrift','outerwear','Navy-Red Color-Block Windbreaker','Navy-Red Color-Block Windbreaker','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',465000,550000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":64,"length":74,"sleeve":63}'),
  ('green-red-retro-windbreaker','thrift','outerwear','Green-Red Retro Windbreaker','Green-Red Retro Windbreaker','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',445000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":62,"length":72,"sleeve":62}'),
  ('blue-logo-hooded-jacket','thrift','outerwear','Blue Logo Hooded Jacket','Blue Logo Hooded Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',525000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":66,"length":76,"sleeve":64}'),
  ('red-hooded-parka','thrift','outerwear','Red Hooded Parka','Red Hooded Parka','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',495000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":61,"length":82,"sleeve":64}'),
  ('orange-harrington-jacket','thrift','outerwear','Orange Harrington Jacket','Orange Harrington Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',395000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":60,"length":66,"sleeve":63}'),
  ('khaki-ma1-bomber','thrift','outerwear','Khaki MA-1 Bomber','Khaki MA-1 Bomber','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',455000,525000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":61,"length":67,"sleeve":64}'),
  ('sherpa-collar-denim-jacket','thrift','outerwear','Corduroy-Collar Denim Jacket','Corduroy-Collar Denim Jacket','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',485000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":56,"length":64,"sleeve":61}'),
  ('shearling-collar-coat','thrift','outerwear','Shearling Collar Coat','Shearling Collar Coat','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',750000,950000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":60,"length":84,"sleeve":65}'),
  ('brown-tweed-blazer','thrift','outerwear','Brown Tweed Blazer','Brown Tweed Blazer','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',425000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":55,"length":76,"sleeve":62}'),
  ('madras-check-anorak','thrift','outerwear','Madras Check Anorak','Madras Check Anorak','Outerwear vintage dengan karakter kuat, cocok buat layering harian.','Vintage outerwear with real character, great for everyday layering.',395000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":65,"length":74,"sleeve":62}'),
  ('blue-embroidered-work-shirt','thrift','tops','Blue Embroidered Work Shirt','Blue Embroidered Work Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',245000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":59,"length":76,"sleeve":62}'),
  ('aqua-madras-shirt','thrift','tops','Aqua Madras Shirt','Aqua Madras Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',195000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":55,"length":74,"sleeve":61}'),
  ('pink-blue-plaid-shirt','thrift','tops','Pink-Blue Plaid Shirt','Pink-Blue Plaid Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',195000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":58,"length":76,"sleeve":62}'),
  ('red-gold-plaid-shirt','thrift','tops','Red-Gold Plaid Shirt','Red-Gold Plaid Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',215000,255000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":59,"length":77,"sleeve":62}'),
  ('dark-denim-western-shirt','thrift','tops','Dark Denim Western Shirt','Dark Denim Western Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',285000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":56,"length":74,"sleeve":62}'),
  ('floral-print-overshirt','thrift','tops','Floral Print Overshirt','Floral Print Overshirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',265000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":63,"length":78,"sleeve":63}'),
  ('rainbow-stripe-shirt','thrift','tops','Rainbow Stripe Shirt','Rainbow Stripe Shirt','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',235000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":58,"length":76,"sleeve":62}'),
  ('forest-green-polo','merch','tops','Forest Green Polo','Forest Green Polo','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',149000,189000,null,'','','{"pit_to_pit":54,"length":72}'),
  ('white-flag-crewneck-sweater','thrift','tops','White Flag Crewneck Sweater','White Flag Crewneck Sweater','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',325000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"pit_to_pit":60,"length":68,"sleeve":60}'),
  ('burgundy-cable-cardigan','thrift','tops','Burgundy Cable Cardigan','Burgundy Cable Cardigan','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',295000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":56,"length":66,"sleeve":60}'),
  ('green-shawl-cardigan','thrift','tops','Green Shawl Cardigan','Green Shawl Cardigan','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',295000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":58,"length":68,"sleeve":61}'),
  ('navy-crest-cardigan','thrift','tops','Navy Crest Cardigan','Navy Crest Cardigan','Atasan pilihan untuk melengkapi outfit streetwear atau clean fit kamu.','A hand-picked top to round out your streetwear or clean-fit outfit.',315000,375000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"pit_to_pit":58,"length":70,"sleeve":61}'),
  ('brown-suede-tassel-loafers','thrift','footwear','Brown Suede Tassel Loafers','Brown Suede Tassel Loafers','Sepatu preloved yang sudah dibersihkan, sol masih nyaman dipakai.','Pre-loved shoes, cleaned and with plenty of sole left.',545000,650000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"insole":27}'),
  ('burgundy-penny-loafers','thrift','footwear','Burgundy Penny Loafers','Burgundy Penny Loafers','Sepatu preloved yang sudah dibersihkan, sol masih nyaman dipakai.','Pre-loved shoes, cleaned and with plenty of sole left.',595000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"insole":28}'),
  ('blue-leather-driving-loafers','thrift','footwear','Blue Leather Driving Loafers','Blue Leather Driving Loafers','Sepatu preloved yang sudah dibersihkan, sol masih nyaman dipakai.','Pre-loved shoes, cleaned and with plenty of sole left.',425000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"insole":26.5}'),
  ('black-canvas-high-tops','thrift','footwear','Black Canvas High-Tops','Black Canvas High-Tops','Sepatu preloved yang sudah dibersihkan, sol masih nyaman dipakai.','Pre-loved shoes, cleaned and with plenty of sole left.',375000,null,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"insole":25.5}'),
  ('silver-retro-runners','thrift','footwear','Silver Retro Runners','Silver Retro Runners','Sepatu preloved yang sudah dibersihkan, sol masih nyaman dipakai.','Pre-loved shoes, cleaned and with plenty of sole left.',465000,525000,8,'Baik, ada tanda pemakaian ringan yang wajar.','Good, light normal signs of wear.','{"insole":28}'),
  ('plaid-baseball-cap','thrift','accessories','Plaid Baseball Cap','Plaid Baseball Cap','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',175000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{}'),
  ('teal-crest-cap','thrift','accessories','Teal Crest Cap','Teal Crest Cap','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',185000,225000,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{}'),
  ('red-flag-pom-beanie','merch','accessories','Red Flag Pom Beanie','Red Flag Pom Beanie','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',129000,null,null,'','','{}'),
  ('plaid-trapper-hat','thrift','accessories','Plaid Trapper Hat','Plaid Trapper Hat','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',195000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{}'),
  ('navy-canvas-tote','merch','accessories','Navy Canvas Tote','Navy Canvas Tote','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',119000,149000,null,'','','{"width":36,"height":42,"depth":10}'),
  ('charcoal-city-backpack','thrift','accessories','Charcoal City Backpack','Charcoal City Backpack','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',345000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{"width":30,"height":45,"depth":14}'),
  ('tan-croc-leather-belt','thrift','accessories','Tan Croc Leather Belt','Tan Croc Leather Belt','Aksesoris pelengkap gaya, dipilih satu per satu.','A finishing accessory, hand-picked one by one.',165000,null,9,'Sangat baik, minim tanda pemakaian.','Excellent, minimal signs of wear.','{}')
),
created as (
  insert into products (slug, type, category_id, name_id, name_en, description_id, description_en,
    price, compare_at_price, condition_score, condition_note_id, condition_note_en, measurements, status, created_at)
  select v.slug, v.type::product_type, c.id, v.name_id, v.name_en, v.desc_id, v.desc_en,
    v.price, v.compare_at, v.cond, v.cond_id, v.cond_en, v.meas::jsonb, 'active',
    now() - (row_number() over () * interval '7 hours')
  from v join categories c on c.slug = v.cat
  on conflict (slug) do nothing
  returning id, slug
)
select count(*) from created;

insert into product_images (product_id, url, alt, sort)
select p.id, i.url, p.name_id, 0
from (values
  ('khaki-pleated-chinos','/images/products/demo/khaki-pleated-chinos.webp'),
  ('woodland-camo-cargo','/images/products/demo/woodland-camo-cargo.webp'),
  ('leopard-print-wide-pants','/images/products/demo/leopard-print-wide-pants.webp'),
  ('navy-wool-pleated-trousers','/images/products/demo/navy-wool-pleated-trousers.webp'),
  ('light-wash-straight-jeans','/images/products/demo/light-wash-straight-jeans.webp'),
  ('studded-blue-jeans','/images/products/demo/studded-blue-jeans.webp'),
  ('raw-indigo-denim','/images/products/demo/raw-indigo-denim.webp'),
  ('selvedge-red-tab-jeans','/images/products/demo/selvedge-red-tab-jeans.webp'),
  ('usa-colorblock-swim-shorts','/images/products/demo/usa-colorblock-swim-shorts.webp'),
  ('polo-colorblock-shorts','/images/products/demo/polo-colorblock-shorts.webp'),
  ('navy-sport-bike-shorts','/images/products/demo/navy-sport-bike-shorts.webp'),
  ('turquoise-boardshorts','/images/products/demo/turquoise-boardshorts.webp'),
  ('black-leather-zip-jacket','/images/products/demo/black-leather-zip-jacket.webp'),
  ('yellow-canvas-work-jacket','/images/products/demo/yellow-canvas-work-jacket.webp'),
  ('navy-green-varsity-jacket','/images/products/demo/navy-green-varsity-jacket.webp'),
  ('black-stadium-jacket','/images/products/demo/black-stadium-jacket.webp'),
  ('navy-red-colorblock-windbreaker','/images/products/demo/navy-red-colorblock-windbreaker.webp'),
  ('green-red-retro-windbreaker','/images/products/demo/green-red-retro-windbreaker.webp'),
  ('blue-logo-hooded-jacket','/images/products/demo/blue-logo-hooded-jacket.webp'),
  ('red-hooded-parka','/images/products/demo/red-hooded-parka.webp'),
  ('orange-harrington-jacket','/images/products/demo/orange-harrington-jacket.webp'),
  ('khaki-ma1-bomber','/images/products/demo/khaki-ma1-bomber.webp'),
  ('sherpa-collar-denim-jacket','/images/products/demo/sherpa-collar-denim-jacket.webp'),
  ('shearling-collar-coat','/images/products/demo/shearling-collar-coat.webp'),
  ('brown-tweed-blazer','/images/products/demo/brown-tweed-blazer.webp'),
  ('madras-check-anorak','/images/products/demo/madras-check-anorak.webp'),
  ('blue-embroidered-work-shirt','/images/products/demo/blue-embroidered-work-shirt.webp'),
  ('aqua-madras-shirt','/images/products/demo/aqua-madras-shirt.webp'),
  ('pink-blue-plaid-shirt','/images/products/demo/pink-blue-plaid-shirt.webp'),
  ('red-gold-plaid-shirt','/images/products/demo/red-gold-plaid-shirt.webp'),
  ('dark-denim-western-shirt','/images/products/demo/dark-denim-western-shirt.webp'),
  ('floral-print-overshirt','/images/products/demo/floral-print-overshirt.webp'),
  ('rainbow-stripe-shirt','/images/products/demo/rainbow-stripe-shirt.webp'),
  ('forest-green-polo','/images/products/demo/forest-green-polo.webp'),
  ('white-flag-crewneck-sweater','/images/products/demo/white-flag-crewneck-sweater.webp'),
  ('burgundy-cable-cardigan','/images/products/demo/burgundy-cable-cardigan.webp'),
  ('green-shawl-cardigan','/images/products/demo/green-shawl-cardigan.webp'),
  ('navy-crest-cardigan','/images/products/demo/navy-crest-cardigan.webp'),
  ('brown-suede-tassel-loafers','/images/products/demo/brown-suede-tassel-loafers.webp'),
  ('burgundy-penny-loafers','/images/products/demo/burgundy-penny-loafers.webp'),
  ('blue-leather-driving-loafers','/images/products/demo/blue-leather-driving-loafers.webp'),
  ('black-canvas-high-tops','/images/products/demo/black-canvas-high-tops.webp'),
  ('silver-retro-runners','/images/products/demo/silver-retro-runners.webp'),
  ('plaid-baseball-cap','/images/products/demo/plaid-baseball-cap.webp'),
  ('teal-crest-cap','/images/products/demo/teal-crest-cap.webp'),
  ('red-flag-pom-beanie','/images/products/demo/red-flag-pom-beanie.webp'),
  ('plaid-trapper-hat','/images/products/demo/plaid-trapper-hat.webp'),
  ('navy-canvas-tote','/images/products/demo/navy-canvas-tote.webp'),
  ('charcoal-city-backpack','/images/products/demo/charcoal-city-backpack.webp'),
  ('tan-croc-leather-belt','/images/products/demo/tan-croc-leather-belt.webp')
) as i(slug, url)
join products p on p.slug = i.slug
where not exists (select 1 from product_images x where x.product_id = p.id);

with v(slug, size_label, sort, qty) as (values
  ('khaki-pleated-chinos','W32 L30',0,1),
  ('woodland-camo-cargo','W33 L31',0,1),
  ('leopard-print-wide-pants','W29 L30',0,1),
  ('navy-wool-pleated-trousers','W31 L31',0,1),
  ('light-wash-straight-jeans','W32 L32',0,1),
  ('studded-blue-jeans','W30 L31',0,1),
  ('raw-indigo-denim','W33 L32',0,1),
  ('selvedge-red-tab-jeans','W31 L32',0,1),
  ('usa-colorblock-swim-shorts','M',0,1),
  ('polo-colorblock-shorts','L',0,1),
  ('navy-sport-bike-shorts','M',0,1),
  ('turquoise-boardshorts','S',0,3),
  ('turquoise-boardshorts','M',1,4),
  ('turquoise-boardshorts','L',2,4),
  ('turquoise-boardshorts','XL',3,2),
  ('black-leather-zip-jacket','L',0,1),
  ('yellow-canvas-work-jacket','XL',0,1),
  ('navy-green-varsity-jacket','L',0,1),
  ('black-stadium-jacket','M',0,1),
  ('navy-red-colorblock-windbreaker','XL',0,1),
  ('green-red-retro-windbreaker','L',0,1),
  ('blue-logo-hooded-jacket','XL',0,1),
  ('red-hooded-parka','L',0,1),
  ('orange-harrington-jacket','L',0,1),
  ('khaki-ma1-bomber','L',0,1),
  ('sherpa-collar-denim-jacket','M',0,1),
  ('shearling-collar-coat','L',0,1),
  ('brown-tweed-blazer','M',0,1),
  ('madras-check-anorak','XL',0,1),
  ('blue-embroidered-work-shirt','L',0,1),
  ('aqua-madras-shirt','M',0,1),
  ('pink-blue-plaid-shirt','L',0,1),
  ('red-gold-plaid-shirt','L',0,1),
  ('dark-denim-western-shirt','M',0,1),
  ('floral-print-overshirt','XL',0,1),
  ('rainbow-stripe-shirt','L',0,1),
  ('forest-green-polo','S',0,3),
  ('forest-green-polo','M',1,5),
  ('forest-green-polo','L',2,5),
  ('forest-green-polo','XL',3,3),
  ('white-flag-crewneck-sweater','L',0,1),
  ('burgundy-cable-cardigan','M',0,1),
  ('green-shawl-cardigan','L',0,1),
  ('navy-crest-cardigan','L',0,1),
  ('brown-suede-tassel-loafers','EU 42',0,1),
  ('burgundy-penny-loafers','EU 43',0,1),
  ('blue-leather-driving-loafers','EU 41',0,1),
  ('black-canvas-high-tops','EU 40',0,1),
  ('silver-retro-runners','EU 43',0,1),
  ('plaid-baseball-cap','All Size',0,1),
  ('teal-crest-cap','All Size',0,1),
  ('red-flag-pom-beanie','All Size',0,6),
  ('plaid-trapper-hat','All Size',0,1),
  ('navy-canvas-tote','One Size',0,10),
  ('charcoal-city-backpack','One Size',0,1),
  ('tan-croc-leather-belt','90 cm',0,1)
),
ins as (
  insert into variants (product_id, size_label, sku, sort, stock_on_hand)
  select p.id, v.size_label, upper(left(replace(p.slug, '-', ''), 10)) || '-' || v.sort, v.sort, v.qty
  from v join products p on p.slug = v.slug
  on conflict (product_id, size_label) do nothing
  returning id, stock_on_hand
)
insert into stock_movements (variant_id, type, qty, note)
select id, 'restock', stock_on_hand, 'demo catalog seed' from ins;
